### ISSUE TITLE
通过api的位置签到，手势签到，二维码签到全都无效

### ISSUE THREAD

**Issue by goodnighteveryone** [mkdir700/chaoxing_auto_sign#54]
为了使用二维码签到，我将api文件部署到了阿里云轻量服务器上（ps严格按照教程部署的），之后在用post请求测试的时候只有普通签到能够成功，但是返回的code一直是2000，message则一直是当前暂无签到任务，请问老哥这是什么问题呢😂。服务器系统是Ubuntu20.04，python是3.8.5，mongodb是4.4。

**Comment by mkdir700** [comment]
成功签到的任务会被记录至数据库，再次执行签到任务时，会跳过已执行签到任务的id

**Comment by goodnighteveryone** [comment]
可是并没有成功签到啊，只有普通签到能签到成功，其他几种签到并没有执行😂

**Comment by mkdir700** [comment]
好的，我检查下

**Comment by goodnighteveryone** [comment]
如果需要的话我可以提供我api的URL😂

**Comment by mkdir700** [comment]
我看了下位置签到和手势签到卡都是正常的

**Comment by goodnighteveryone** [comment]
老哥你的请求代码是什么啊？我使用的readme里的post方式代码，但其他几种都不行😂，114.55.27.89:9090/sign这是我的url网址,老哥可以测试一下吗？还有api还是无法签二维码的吗😂

**Comment by mkdir700** [comment]
api版本我在改了，需要提交`enc`就可以了

**Comment by goodnighteveryone** [comment]
老哥，麻烦帮看一下为啥我测试的时候除了普通签到之外其他的都不行啊😂代码用的这个：import requests

# POST
params = {
    'username': 'xxxxx',
    'password': 'xxxxx',
    'schoolid': '',
    'sckey': '',
    'enc': ''  #  扫码签到必填
}
requests.post('http://xxxxxxx:9090/sign', params=params)

**Comment by mkdir700** [comment]
我修改了api的版本，你重新clone，试下

**Comment by goodnighteveryone** [comment]
好的

**Comment by goodnighteveryone** [comment]
重新部署之后报错如下：
cookies失效
登录成功
Traceback (most recent call last):
  File "./cloud_sign.py", line 277, in interface
    result = await auto_sign.start_sign_tasks(client)
  File "./cloud_sign.py", line 204, in start_sign_tasks
    classid_courseId = await self.get_all_classid(client)
  File "./cloud_sign.py", line 122, in get_all_classid
    assert resp.status_code == 200
AttributeError: 'ClientResponse' object has no attribute 'status_code'

**Comment by mkdir700** [comment]
将cloud_sign.py 中122行 修改为 
```python
assert resp.status == 200
```

**Comment by goodnighteveryone** [comment]
![image](https://user-images.githubusercontent.com/49894559/114153000-763c5c00-9951-11eb-9fc8-0673b29ed2c4.png)
122行代码一开始就是这个，我重新输入之后还是一样的报错

**Comment by goodnighteveryone** [comment]
![image](https://user-images.githubusercontent.com/49894559/114153704-3033c800-9952-11eb-9a44-e6669d48baa8.png)
改了之后仍然报错：
cookies失效
登录成功
Traceback (most recent call last):
  File "./cloud_sign.py", line 277, in interface
    result = await auto_sign.start_sign_tasks(client)
  File "./cloud_sign.py", line 204, in start_sign_tasks
    classid_courseId = await self.get_all_classid(client)
  File "./cloud_sign.py", line 122, in get_all_classid
    assert resp.status == 200

**Comment by mkdir700** [comment]
把这行删了试试

**Comment by goodnighteveryone** [comment]
报错变为这个：
cookies失效
登录成功
Traceback (most recent call last):
  File "./cloud_sign.py", line 277, in interface
  File "./cloud_sign.py", line 204, in start_sign_tasks
  File "./cloud_sign.py", line 122, in get_all_classid
    text = await resp.text()
AssertionError

**Comment by mkdir700** [comment]
在本地测试，是正常的。这个就有点奇怪了

**Comment by goodnighteveryone** [comment]
可能是mongodb的问题，我重装之后就不报错了，无论是status_code、status还是删除那行都不报错，不过不执行签到任务，任务输出为这个：
![image](https://user-images.githubusercontent.com/49894559/114159453-6411ec00-9958-11eb-90d3-9f8ed0274ba5.png)

**Comment by xiao-baii** [comment]
阿里云和腾讯云的ip被超星屏蔽了，签到无法使用的。

**Comment by FKDXD** [comment]
> 
我在服务器上面的本地版可以用，api就4000，腾讯云

**Comment by FKDXD** [comment]
看不懂啊
![学习通](https://user-images.githubusercontent.com/73707568/143894908-21ae721a-d3a8-44f0-ab5c-b75c2c100f24.png)

**Comment by FKDXD** [comment]
看不懂
![学习通](https://user-images.githubusercontent.com/73707568/143895088-3e8c3a22-b2d2-4d09-a646-df1a364f7873.png)
