### ISSUE TITLE
云函数部署运行的时候发生如下错误

### ISSUE THREAD

**Issue by LLinVIP** [mkdir700/chaoxing_auto_sign#62]
![IMG_20210423_204844](https://user-images.githubusercontent.com/68938689/115873469-8dad3600-a475-11eb-9cd5-7eabf6c66774.jpg)
如图所示

**Comment by mkdir700** [comment]
使用以下命令运行试试

```
python main.py
```

**Comment by mkdir700** [comment]
修改main.py 最下面一行代码为
```python
uvicorn.run(app, host="0.0.0.0", port=9090)
```
或者
重新clone一下.
另外这个是API版本的。

**Comment by LLinVIP** [comment]
感谢大佬，已经可以跑起来，但会出现此错误
![Uploading IMG_20210424_164812__01.jpg…]()

**Comment by mkdir700** [comment]
异常信息复制完整一点，下面的报错看不到

**Comment by LLinVIP** [comment]
INFO:     122.192.219.152:2573 - "GET /favicon.ico HTTP/1.1" 404 Not Found
Traceback (most recent call last):
  File "/home/ysk/Downloads/chaoxing_auto_sign-latest/api/cloud_sign.py", line 267, in interface
    auto_sign= AutoSign(username=payload[&apos;username&apos;],
  File "/home/ysk/Downloads/chaoxing_auto_sign-latest/api/cloud_sign.py", line 29, in __init__
    self.mongo = SignMongoDB(username)
  File "/home/ysk/Downloads/chaoxing_auto_sign-latest/api/db_handler.py", line 11, in __init__
    if not self.collection.find_one({"username": username}):
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/topology.py", line 482, in get_server_session
    self._select_servers_loop(
  File "/home/ysk/.local/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

**Comment by mkdir700** [comment]
1. 你没有安装MongoDB
2. MongoDB设置了密码
