### ISSUE TITLE
APi测试提示如下

### ISSUE THREAD

**Issue by why20hh** [mkdir700/chaoxing_auto_sign#72]
Traceback (most recent call last):
  File "/root/chaoxing_auto_sign/api/cloud_sign.py", line 284, in interface
    auto_sign= AutoSign(username=payload['username'],
  File "/root/chaoxing_auto_sign/api/cloud_sign.py", line 29, in __init__
    self.mongo = SignMongoDB(username)
  File "/root/chaoxing_auto_sign/api/db_handler.py", line 19, in __init__
    if not self.collection.find_one({"username": username}):
  File "/opt/python39/lib/python3.9/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/opt/python39/lib/python3.9/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/opt/python39/lib/python3.9/site-packages/pymongo/cursor.py", line 1073, in _refresh
    self.__send_message(q)
  File "/opt/python39/lib/python3.9/site-packages/pymongo/cursor.py", line 953, in __send_message
    response = client._run_operation_with_response(
  File "/opt/python39/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1342, in _run_operation_with_response
    return self._retryable_read(
  File "/opt/python39/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/opt/python39/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1334, in _cmd
    return server.run_operation_with_response(
  File "/opt/python39/lib/python3.9/site-packages/pymongo/server.py", line 136, in run_operation_with_response
    _check_command_response(first)
  File "/opt/python39/lib/python3.9/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on signweb to execute command { find: "users", filter: { username: "xxxxxxxxxxx" }, limit: 1, singleBatch: true, lsid: { id: UUID("033b5a0d-ebc5-41c9-b59f-dd6a63c911c5") }, $db: "signweb", $readPreference: { mode: "primaryPreferred" } }

这是哪里错了，需要怎么改呢

**Comment by mkdir700** [comment]
操作mongodb的账户权限不足
