### ISSUE TITLE
事件循环报错

### ISSUE THREAD

**Issue by aquaupa** [mkdir700/chaoxing_auto_sign#79]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/venv/study_script/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/venv/study_script/chaoxing_auto_sign/local/main.py", line 55, in start
    loop = asyncio.new_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 58, in __init__
    selector = selectors.DefaultSelector()
  File "/usr/lib/python3.9/selectors.py", line 350, in __init__
    self._selector = self._selector_cls()
OSError: [Errno 24] Too many open files
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fb71f7550>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/base_events.py", line 683, in __del__
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 92, in close
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 99, in _close_self_pipe
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
Job "start (trigger: interval[0:05:00], next run at: 2021-09-18 07:19:38 CST)" raised an exception
Traceback (most recent call last):
  File "/home/pi/venv/study_script/chaoxing_auto_sign/local/main.py", line 53, in start
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

**Comment by aquaupa** [comment]
程序重启又好了，不知道什么时候出错的

**Comment by shanyan-wcx** [comment]
+1
